##
##  Innocent Whizbang
##  Written by Sam Reaves and Donald Gary
##  May 2 2017
##

version: "2"

services:
  espeak-api:
    build: ./packages/espeak-api
    #image: samreaves/espeak-test:0.0.4

    # Mount volume of local files
    volumes:
      - "./voice-files:/src/voice-files"

    # Map machines port 80 with container's 3000
    ports:
      - "80:3000"
